import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.security.MessageDigest
import java.util.zip.ZipFile

plugins {
    id("net.fabricmc.fabric-loom")
    `java-library`
    `maven-publish`
    id("org.jetbrains.kotlin.jvm") version "2.4.0"
}

version = providers.gradleProperty("mod_version").get()
group = providers.gradleProperty("maven_group").get()

loom {
    accessWidenerPath = file("src/main/resources/blackskija.accesswidener")

    // Portable client run configs that force the GPU backend via a launch arg (overrides options.txt),
    // so GL vs Vulkan is one click with no file editing. Loom generates the machine-specific IDE
    // configs from these on sync — the generated XMLs stay local (see .gitignore), this is the source.
    runs {
        create("clientVulkan") {
            client()
            configName = "Minecraft Client (Vulkan)"
            programArgs("--graphicsBackend", "vulkan")
            // Marker so the dev showcase runs ONLY in BlackSkija's own dev, never in a
            // consumer mod's dev run (which also has isDevelopmentEnvironment). See BlackskijaClient.
            property("blackskija.demo", "true")
        }
        create("clientOpenGl") {
            client()
            configName = "Minecraft Client (OpenGL)"
            programArgs("--graphicsBackend", "opengl")
            property("blackskija.demo", "true")
        }
    }
}

repositories {
    mavenCentral()
}

// Platform natives are NOT bundled; this configuration only resolves them at build time,
// so `generateSkijaHashes` can fingerprint each one into a manifest that SkijaNatives
// verifies at runtime. Gradle's own download + checksum makes these a trusted source.
val skijaNatives = configurations.create("skijaNatives") { isTransitive = false }

dependencies {
    minecraft("com.mojang:minecraft:${providers.gradleProperty("minecraft_version").get()}")
    implementation("net.fabricmc:fabric-loader:${providers.gradleProperty("loader_version").get()}")

    implementation("net.fabricmc.fabric-api:fabric-api:${providers.gradleProperty("fabric_api_version").get()}")
    implementation("net.fabricmc:fabric-language-kotlin:${providers.gradleProperty("fabric_kotlin_version").get()}")

    val skijaVersion = providers.gradleProperty("skija_version").get()
    api("io.github.humbleui:skija-shared:$skijaVersion")
    include("io.github.humbleui:skija-shared:$skijaVersion")

    // skija-shared needs io.github.humbleui:types at runtime (Rect/RRect/Point, which the native's
    // _nAfterLoad resolves via FindClass). include() isn't transitive, so bundle it explicitly, or the
    // installed mod crashes in DirectContext init. Dev works regardless because Gradle adds it transitively.
    val typesVersion = providers.gradleProperty("types_version").get()
    api("io.github.humbleui:types:$typesVersion")
    include("io.github.humbleui:types:$typesVersion")

    // Resolved only to fingerprint (see generateSkijaHashes); not on any classpath.
    for (platform in listOf("windows-x64", "linux-x64", "macos-x64", "macos-arm64")) {
        skijaNatives("io.github.humbleui:skija-$platform:$skijaVersion")
    }
}

tasks.processResources {
    val properties = mapOf(
        "version" to version,
        "minecraft_version" to providers.gradleProperty("minecraft_version").get(),
        "loader_version" to providers.gradleProperty("loader_version").get(),
        "kotlin_loader_version" to providers.gradleProperty("fabric_kotlin_version").get(),
        "skija_version" to providers.gradleProperty("skija_version").get(),
    )

    properties.forEach { (key, value) -> inputs.property(key, value) }
    filteringCharset = "UTF-8"

    filesMatching(listOf("fabric.mod.json", "blackskija/skija.version")) {
        expand(properties)
    }
}

val skijaHashesDir = layout.buildDirectory.dir("generated/skija-hashes")

val generateSkijaHashes = tasks.register("generateSkijaHashes") {
    val skijaVersion = providers.gradleProperty("skija_version").get()
    val nativeJars = skijaNatives
    val outFile = skijaHashesDir.map { it.file("blackskija/skija.sha256") }
    inputs.property("skijaVersion", skijaVersion)
    inputs.files(nativeJars)
    outputs.file(outFile)
    doLast {
        val libByOs = mapOf("windows" to "skija.dll", "linux" to "libskija.so", "macos" to "libskija.dylib")
        val sb = StringBuilder()
        sb.appendLine("# Generated by generateSkijaHashes — do not edit by hand.")
        sb.appendLine("version=$skijaVersion")
        nativeJars.files.sortedBy { it.name }.forEach { jar ->
            val classifier = jar.name.removePrefix("skija-").removeSuffix("-$skijaVersion.jar")
            val os = classifier.substringBefore('-')
            val arch = classifier.substringAfter('-')
            val prefix = "io/github/humbleui/skija/$os/$arch/"
            val needed = buildList {
                add(libByOs.getValue(os))
                if (os == "windows") add("icudtl.dat")
            }
            ZipFile(jar).use { zip ->
                needed.forEach { name ->
                    val entry = zip.getEntry(prefix + name) ?: error("$name not in ${jar.name}")
                    val md = MessageDigest.getInstance("SHA-256")
                    zip.getInputStream(entry).use { input ->
                        val buf = ByteArray(1 shl 16)
                        while (true) {
                            val n = input.read(buf)
                            if (n < 0) break
                            md.update(buf, 0, n)
                        }
                    }
                    sb.appendLine("$classifier/$name=" + md.digest().joinToString("") { "%02x".format(it) })
                }
            }
        }
        val f = outFile.get().asFile
        f.parentFile.mkdirs()
        f.writeText(sb.toString())
    }
}

tasks.processResources {
    dependsOn(generateSkijaHashes)
    from(skijaHashesDir)
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_25
    }
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.jar {
    val projectName = project.name
    inputs.property("projectName", projectName)

    from("LICENSE.txt") {
        rename { "${it}_$projectName" }
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = project.name
            from(components["java"])
        }
    }
}
