import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.security.MessageDigest
import java.util.zip.ZipFile

/**
 * The version-neutral half of every BlackSkija platform: Java 25 toolchain, the shared source tree,
 * the Skija dependency, and the native-fingerprint manifest. Loom and everything version-specific
 * (Minecraft/Fabric coordinates, access widener, run configs) is applied by the platform module —
 * `pluginManagement` in settings.gradle.kts does not reach buildSrc's classpath, so a precompiled
 * script plugin cannot apply Loom itself.
 */

plugins {
    kotlin("jvm")
    `java-library`
    `maven-publish`
}

fun prop(name: String): String = providers.gradleProperty(name).get()

group = prop("maven_group")
version = prop("mod_version")

// Both 26.1.2 and 26.2 are Java 25 (class-file major 69).
val targetJava = 25

base {
    archivesName = "blackskija-${project.name}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(targetJava)
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven("https://maven.fabricmc.net/") { name = "Fabric" }
}

// The shared half of the library: one source tree, compiled against each platform's own mappings.
// A source directory rather than a module because it references Minecraft — a binary module can only
// bind one version's mappings, these files must bind both.
sourceSets.named("main") {
    java.srcDir(rootProject.file("platform/shared/src/main/java"))
    resources.srcDir(rootProject.file("platform/shared/src/main/resources"))
}
kotlin {
    sourceSets.named("main") {
        kotlin.srcDir(rootProject.file("platform/shared/src/main/kotlin"))
    }
}

dependencies {
    api("io.github.humbleui:skija-shared:${prop("skija_version")}")
    // skija-shared resolves Rect/RRect/Point via FindClass in the native's _nAfterLoad, so types must
    // be present at runtime; the platform module JiJ-bundles both.
    api("io.github.humbleui:types:${prop("types_version")}")
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release = targetJava
}
tasks.withType<KotlinCompile>().configureEach {
    compilerOptions.jvmTarget = JvmTarget.fromTarget(targetJava.toString())
}

// ── Skija native fingerprinting ────────────────────────────────────────────
// Natives are NOT bundled; this configuration only resolves them at build time so the manifest can
// fingerprint each one for SkijaNatives to verify the runtime download against. Version-neutral.
val skijaNatives = configurations.create("skijaNatives") { isTransitive = false }
dependencies {
    val skijaVersion = prop("skija_version")
    for (platform in listOf("windows-x64", "linux-x64", "macos-x64", "macos-arm64"))
        skijaNatives("io.github.humbleui:skija-$platform:$skijaVersion")
}

val skijaHashesDir = layout.buildDirectory.dir("generated/skija-hashes")

val generateSkijaHashes = tasks.register("generateSkijaHashes") {
    val skijaVersion = prop("skija_version")
    val nativeJars = skijaNatives
    val outFile = skijaHashesDir.map { it.file("blackskija/skija.sha256") }
    inputs.property("skijaVersion", skijaVersion)
    inputs.files(nativeJars)
    outputs.file(outFile)
    doLast {
        val libByOs = mapOf("windows" to "skija.dll", "linux" to "libskija.so", "macos" to "libskija.dylib")
        val sb = StringBuilder()
        sb.appendLine("# Generated by generateSkijaHashes — do not edit by hand.")
        sb.appendLine("version=$skijaVersion")
        nativeJars.files.sortedBy { it.name }.forEach { jar ->
            val classifier = jar.name.removePrefix("skija-").removeSuffix("-$skijaVersion.jar")
            val os = classifier.substringBefore('-')
            val arch = classifier.substringAfter('-')
            val prefix = "io/github/humbleui/skija/$os/$arch/"
            val needed = buildList {
                add(libByOs.getValue(os))
                if (os == "windows") add("icudtl.dat")
            }
            ZipFile(jar).use { zip ->
                needed.forEach { name ->
                    val entry = zip.getEntry(prefix + name) ?: error("$name not in ${jar.name}")
                    val md = MessageDigest.getInstance("SHA-256")
                    zip.getInputStream(entry).use { input ->
                        val buf = ByteArray(1 shl 16)
                        while (true) {
                            val n = input.read(buf)
                            if (n < 0) break
                            md.update(buf, 0, n)
                        }
                    }
                    sb.appendLine("$classifier/$name=" + md.digest().joinToString("") { "%02x".format(it) })
                }
            }
        }
        val f = outFile.get().asFile
        f.parentFile.mkdirs()
        f.writeText(sb.toString())
    }
}

tasks.named<ProcessResources>("processResources") {
    dependsOn(generateSkijaHashes)
    from(skijaHashesDir)
}

tasks.named<Jar>("jar") {
    from(rootProject.file("LICENSE.txt")) {
        rename { "${it}_${base.archivesName.get()}" }
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = "blackskija-${project.name}"
            from(components["java"])
        }
    }
}
